FW: Update Makefiles to handle sdld errors better and clean output
Now if sdld exit with an error code the make process will detect this.

Also fixed the error where a base address was set for the non-existing
_DATA section.

Switched to a hopefully more portable way to work around the problem,
where echo interprets the '-e' command as an option. The current
solution to use the '-e' was not portable.

Finally hide command output and instead print user friendly strings.

diff --git a/firmware/nvm_dump/Makefile b/firmware/nvm_dump/Makefile
--- a/firmware/nvm_dump/Makefile
+++ b/firmware/nvm_dump/Makefile
@@ -23,6 +23,7 @@ clean:
 # The "o" option is mandatory, as the linker requires list, object and symbol files to generate executables. The "ff" and "p" options generate a readable list file. The "g" option tells the assembler to not generate an error if it finds an undefined symbol that is not declared as external.
 #
 %.rel: %.asm
+	@echo "ASM $<"; \
 	/usr/bin/sdas8051 -wloffgp "$<"
 
 #
@@ -30,24 +31,32 @@ clean:
 #  -i		Output Intel Hex
 #  -m		Generate a map file
 #  -b		Set base address of area
-#  -e		end (= echo -e "\x2de", this to prevent echo from eating the '-e' option)
+#  -e		end
+#
+#  WARNING: The <space> before the '-' in the echo(1) command is there on
+#  purpose to prevent echo(1) from interpreting the '-' as an option(ie. '-e')
+#  Yes, if your filename starts with a '-' it will also cause problems...
+#
+#  Sometimes sdld(1) returns with an error code but still generates the output
+#  file. To fix this the extra rm(1) command is added on failure.
 %.ihx: %.rel
+	@echo "LD $@"; \
 	{ \
-		echo "-i"; \
-		echo "-m"; \
-		echo "-w"; \
-		echo "-b _DATA = 0x40"; \
+		echo " -i"; \
+		echo " -m"; \
+		echo " -w"; \
 		for f in $^; do \
 			echo $$f ; \
 		done ; \
-		echo -e "\x2de" ; \
-	} | sdld -c; echo; \
+		echo ' -e'; \
+	} | sdld -n -c || { rm "$@"; false; }
 
 %.bin: %.ihx
+	@echo "MAKEBIN $@"; \
 	makebin -p < "$<" > "$@"
 
 %_generated.c: %.bin
-	@echo "Generating $@"; \
+	@echo "CUSTOM $@"; \
 	{ \
 		echo "/* WARNING: THIS FILE IS AUTO GENERATED BY THE NVM_DUMP BUILD PROCESS */" ;\
 		echo "// NVM_Dump firmware";\
